name: CI

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev
        
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: ./Build.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: artifacts
          path: artifacts/**/*
